
- name: "install fuseki version 3.14"
  hosts: "localhost"
  remote_user: runner
  tasks:
  - import_role:
      name: "fuseki"
    vars:
      fuseki_version: "4.4.0"
      fuseki_allow_httpd: false
      fuseki_java_opts: "-Xmx1g\\s-server"
      fuseki_compacting: false
      fuseki_lucene: true
      fuseki_configurations:
      - name: "stedsnavn-data"
        union_default_graph: true
        compacting: false
        read_write: true
        dataset_type: "tdb2"
        spatial: false
        lucene: true
        entity_map: |
         text:defaultField     "label" ;
         text:entityField      "uri" ;
         text:uidField         "uid" ;
         text:langField        "lang" ;
         text:graphField       "graph" ;
         text:map (
         [ text:field "label" ;
           text:predicate rdfs:label ]
         )
  - name: "wait for endpoint to be started"
    wait_for:
      port: 3030
      state: started

  - name: "publish test data to graph store on write endpoint"
    shell: "curl -v -f -H 'Content-type: application/n-triples'  -H 'Transfer-Encoding: chunked' -X PUT -T test.nt localhost:3030/stedsnavn-data_write/data?graph=http://data.stadnamn.uib.no/stedsnavn/rygh"

  - name: "debug"
    shell: ls /opt/ -alh && ls /var/ -alh
    register: jena_home_content

  - name: "debug folder content"
    debug:
      msg: "{{ jena_home_content }}"

  - name: "stop fuseki, index lucene, start fuseki"
    shell:
      chdir: "/opt/jena-fuseki"
      cmd: |
       sudo /usr/bin/systemctl stop fuseki.service &&
       cd /var/fuseki/databases/stedsnavn-data &&
       rm -rf Lucene &&
       java -cp /opt/apache-jena-fuseki/fuseki-server.jar jena.textindexer --desc=/var/fuseki/configuration/stedsnavn-data.ttl &&
       sudo /usr/bin/systemctl start fuseki.service
    become_user: fuseki
    become: true
    environment:
      FUSEKI_HOME: "/opt/jena-fuseki"

  - name: "import tasks"
    import_tasks: "query-tdb2-service.yml"

  - name: "query test endpoint"
    debug:
      msg: "test"

  - name: "view database directory"
    debug:
      msg: "test"

  - name: "upgrade endpoint"
    debug:
      msg: "test"

  - name: "run query from fuseki"
    debug:
      msg: "test"

  - name: "stop fuseki service"
    debug:
      msg: "test"

  - name: "run query from tdb2.query on directory"
    debug:
      msg: "test"

