galaxy_info:
  role_name: fuseki
  author: paginagmbh
  description: Apache Jena/Fuseki SPARQL Server
  company: Pagina GmbH
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - database
    - web
    - nosql
    - semantic
    - rdf
dependencies: []