name: "run tests for upgrading fuskeki (persistent data disappearing from named graphs)"
on:
  workflow_dispatch
jobs:
  build:
    strategy:
      fail-fast: false
    matrix: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2

    - name: "install ansible"
      run: "sudo apt-get install -y ansible"
