name: "run tests for upgrading fuskeki (persistent data disappearing from named graphs)"
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-20.04
    container: rockylinux:8
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2

    - name: "install ansible"
      run: "whoami && yum install -y epel-release && yum install -y ansible sudo"

    - name: "run ansible playbook"
      run: "ansible-playbook test-tdb2-upgrade.yml"
