name: "run tests for upgrading fuskeki (persistent data disappearing from named graphs)"
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2

    - name: "install ansible"
      run: "pip3 install wheel && pip3 install ansible==2.10.7"

    - name: "run ansible playbook"
      run: "ansible-playbook test-tdb2-upgrade.yml"
